// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDciokQWIUQclwhWGBc2TQy058nFbKA44w',
    appId: '1:1050931532816:web:25491fcebd308270cb6695',
    messagingSenderId: '1050931532816',
    projectId: 'app-hoctap',
    authDomain: 'app-hoctap.firebaseapp.com',
    storageBucket: 'app-hoctap.firebasestorage.app',
    measurementId: 'G-9118JFYW39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCySJPIEJhsaAy6d_3FkPw6WuDD4lAdnuY',
    appId: '1:1050931532816:android:b8cb9e2ec46e0d41cb6695',
    messagingSenderId: '1050931532816',
    projectId: 'app-hoctap',
    storageBucket: 'app-hoctap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD07ArEOUsmqJal8Vk4fIFkVPPbcDpiy4k',
    appId: '1:1050931532816:ios:543572381e4c2c93cb6695',
    messagingSenderId: '1050931532816',
    projectId: 'app-hoctap',
    storageBucket: 'app-hoctap.firebasestorage.app',
    iosClientId: '1050931532816-10p0uh5utnl0m302i3i5n8fq9a057e8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.appHoctap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD07ArEOUsmqJal8Vk4fIFkVPPbcDpiy4k',
    appId: '1:1050931532816:ios:543572381e4c2c93cb6695',
    messagingSenderId: '1050931532816',
    projectId: 'app-hoctap',
    storageBucket: 'app-hoctap.firebasestorage.app',
    iosClientId: '1050931532816-10p0uh5utnl0m302i3i5n8fq9a057e8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.appHoctap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDciokQWIUQclwhWGBc2TQy058nFbKA44w',
    appId: '1:1050931532816:web:6511fe3522441eebcb6695',
    messagingSenderId: '1050931532816',
    projectId: 'app-hoctap',
    authDomain: 'app-hoctap.firebaseapp.com',
    storageBucket: 'app-hoctap.firebasestorage.app',
    measurementId: 'G-HE78F03GM0',
  );

}